- name: Deploy Awesome website
  hosts: all
  vars:
    index_title: Awesome website
    index_content: Awesome website
    index_foot: Hosted on {{ ansible_hostname }}.

  tasks:
  - when: command == 'deploy'
    block:
      - name: httpd package is present
        yum:
          name: httpd

      - name: latest index.html file is present
        template:
          src: index.html.j2
          dest: /var/www/html/index.html
          owner: apache
          group: apache

  - when: command == 'deploy' or command == 'start'      
    name: Awesome website is started
    service:
      name: httpd
      state: started

  - when: command == 'stop'
    name: Awesome website is stopped
    service:
      name: httpd
      state: stopped
