- name: Manage Awesome website
  hosts: all
  vars:
    index_title: Awesome website
    index_content: Welcome to Ansible Automates !
    index_foot: Hosted on {{ ansible_hostname }}
    int_address: '{{ inventory_hostname }}'
    
  tasks:
  - when: command == 'deploy'
    become: true
    block:
      - name: httpd package is present
        yum:
          name: httpd

      - name: latest index.html file is present
        template:
          src: index.html.j2
          dest: /var/www/html/index.html
          owner: apache
          group: apache

  - when: command == 'deploy' or command == 'start'
    name: Awesome website is started
    become: true
    service:
      name: httpd
      state: started

  - when: command == 'stop'
    name: Awesome website is stopped
    become: true
    service:
      name: httpd
      state: stopped

  - when: command == 'smoke_test'
    name: Awesome website is responding locally
    uri:
      url: 'http://localhost/'
      return_content: true
    register: test_local

  - when: command == 'smoke_test'
    name: Awesome website is responding internally
    uri:
      url: 'http://{{ int_address }}/'
      return_content: true
    delegate_to: localhost
    register: test_internal
