# This playbook is meant to be called with ansible-pull
# This is the default playbook if hostname is not found in this repo
- name: Deploy Awesome website
  hosts: all
  vars:
    index_title: Awesome website
    index_content: |
                Hosted on {{ ansible_hostname }}.

  tasks:
  - name: httpd package is present
    yum:
      name: httpd

  - name: latest index.html file is present
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache

  - name: httpd is started
    service:
      name: httpd
      state: started

  - debug:
      msg: Successful deployment on '{{ ansible_ssh_host }}'
