- name: DNF Rollback
  hosts: all
  become: true

  tasks:
    - name: Rollback to transaction ID {{ target_transaction_id }}
      command: dnf history rollback {{ target_transaction_id }} -y
      register: dnf_result
      changed_when: 
        - "'Nothing to do' not in dnf_result.stdout"
        - dnf_result.rc == 0
