- name: Deploy Insights agent
  hosts: all
  become: true

  tasks:
    - name: Ensure Insights Client is properly installed
      package:
        name:
          - insights-client
          - python3-requests
          - python3-urllib3
        state: '{{ item }}'
      loop:
        - absent
        - present
      when: command == 'register'

    - name: Register to the Red Hat Insights Service
      command: insights-client --register --display-name={{ ansible_fqdn }}
      when: command == 'register'

    - name: Check Insights Client status
      command: insights-client --status
      changed_when: false

    - name: Upload latest Insights state
      command: insights-client
      when: command == 'refresh'
