- name: Deploy Insights agent
  hosts: all
  become: true

  tasks:
    - name: Install Red Hat Access Insights Client
      package:
        name: insights-client

    - name: Register to the Red Hat Insights Service
      command: insights-client --register --display-name={{ ansible_fqdn }}
      args:
        creates: /etc/redhat-access-insights/.registered

    - name: Upload latest Insights state
      command: insights-client
