- name: Deploy Insights agent
  hosts: all
  become: true

  tasks:
    - name: Install Red Hat Insights Client
      package:
        name: insights-client

    - name: Check Insights Client status
      command: insights-client --status
      register: insights_status

    - name: Register to the Red Hat Insights Service
      command: insights-client --register --display-name={{ ansible_fqdn }}
      register: insights_register
      changed_when: false

    - name: Upload latest Insights state
      command: insights-client
