- name: Insights Client actions
  hosts: all
  become: true

  tasks:
    - name: Ensure Insights components are installed
      package:
        name:
          - insights-client
          - openscap
          - scap-security-guide
          - openscap-scanner
          - yara
      when: command == 'install'

    - name: Register to the Red Hat Insights Service
      command: insights-client --register #--display-name={{ ansible_fqdn }}
      when: command == 'register'

    - name: Upload latest Insights analytics
      command: insights-client
      when: command == 'refresh'

    - name: Upload latest Compliance state
      command: insights-client --compliance
      when: command == 'compliance'
