# This playbook is meant to be called with ansible-pull
# This is the default playbook if hostname is not found in this repo
- name: Deploy basic web server (self-service)
  hosts: all
  vars:
    index_title: Awesome web server
    index_content: |
                Welcome on {{ ansible_hostname | upper }}
                <br>This is the {{ app_name | default('Green') }} application web server </br>
    
  tasks:
  - name: httpd package is present
    yum:
      name: httpd

  - name: latest index.html file is present
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache

  - name: httpd is started
    service:
      name: httpd
      state: started
