# This playbook is meant to be called with ansible-pull
# This is the default playbook if hostname is not found in this repo
- name: Deploy basic web server (self-service)
  hosts: localhost
  vars:
    index_title: Awesome web server
    index_content: |
                I am {{ ansible_hostname | upper }} !
                This web server was installed with ansible-pull
    
  tasks:
  - name: httpd package is present
    yum:
      name: httpd

  - name: latest index.html file is present
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: apache
      group: apache

  - name: httpd is started
    service:
      name: httpd
      state: started
