- name: Patch System by Type or ID
  hosts: all

  tasks:
    - name: Patch errata by type {{ errata_type }}
      dnf:
        name: *
        state: latest
        security: '{{ erata_type == "security" | default(omit) }}'
        bugfix: '{{ erata_type == "bugfix" | default(omit) }}'
      when: errata_type is defined
      
    - name: Apply outstanding fix {{ rhsa_id }}
      dnf:
        name: "{{ rhsa_id }}"
      when: rhsa_id is defined
