- name: Patch System by Errata Type or ID
  hosts: all
  become: true

  tasks:
    - name: Patch errata by type {{ errata_type }}
      dnf:
        name: '*'
        state: latest
        security: '{{ errata_type == "security" | default(omit) }}'
        bugfix: '{{ errata_type == "bugfix" | default(omit) }}'
      when: errata_type is defined
      
    - name: Apply outstanding fix {{ errata_id }}
      command: dnf update --advisory {{ errata_id }} -y
      when: errata_id is defined
      register: dnf_result
      changed_when: 
        - "'Nothing to do' not in dnf_result.stdout"
        - dnf_result.rc == 0
      failed_when:
        - "'Nothing to do' not in dnf_result.stdout"
        - dnf_result.rc != 0
