- name: Patch System by Errata Type or ID
  hosts: all

  tasks:
    - name: Patch errata by type {{ errata_type }}
      dnf:
        name: *
        state: latest
        security: '{{ errata_type == "security" | default(omit) }}'
        bugfix: '{{ errata_type == "bugfix" | default(omit) }}'
      when: errata_type is defined
      
    - name: Apply outstanding fix {{ errata_id }}
      dnf:
        name: '{{ errata_id }}'
      when: errata_id is defined
