- name: Register to RHSM
  hosts: all
  gather_facts: false

  tasks:
    - name: Register to RHSM
      redhat_subscription:
        username: '{{ rhsm_username | default(omit) }}'
        password: '{{ rhsm_password | default(omit) }}'
        auto_attach: true
        state: "{{ rhsm_state | deafult('present') }}"
