- name: Manage Content View Date Filter
  hosts: localhost
  gather_facts: no
  vars:
    filter_name: "Include patches up to this date"

  tasks:
    - name: CV Filter is {{ filter_state }}
      redhat.satellite.content_view_filter:
        server_url: '{{ satellite_url }}'
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: false
        organization: '{{ satellite_organization }}'
        content_view: '{{ item }}'
        name: '{{ filter_name }}'
        filter_type: erratum
        inclusion: true
        state: '{{ filter_state }}'
      loop : '{{ cv_list }}'
      notify: publish_new_version
    
    - name: CV Filter rule is {{ filter_state }} with data limit {{ filter_date }}
      redhat.satellite.content_view_filter_rule:
        server_url: '{{ satellite_url }}'
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: false
        organization: '{{ satellite_organization }}'
        content_view: '{{ item }}'
        content_view_filter: '{{ filter_name }}'
        end_date: '{{ filter_date | string }}'
        types:
          - security
          - enhancement
          - bugfix
        state: '{{ filter_state }}'
      loop : '{{ cv_list }}'
      notify: publish_new_version

  handlers:
    - name: publish_new_version
      redhat.satellite.content_view_version:
        server_url: '{{ satellite_url }}'
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: false
        organization: '{{ satellite_organization }}'
        content_view: '{{ item }}'
        state: present
      loop : '{{ cv_list }}'
