- name: Manage Content View Date Filter
  hosts: localhost
  gather_facts: no

  tasks:
    # - name: CV Filter is {{ filter_state }}
    #   redhat.satellite.content_view_filter:
    #     server_url: '{{ satellite_url }}'
    #     username: '{{ satellite_username }}'
    #     password: '{{ satellite_password }}'
    #     validate_certs: no
    #     organization: '{{ satellite_organization }}'
    #     content_view: '{{ item }}'
    #     name: '{{ filter_name }}'
    #     filter_type: erratum
    #     inclusion: true
    #     state: '{{ filter_state }}'
    #   loop : '{{ cv_list }}'
    
    - name: CV Filter is present
      command: hammer content-view filter create --organization-id 1 --content-view {{ item }} --name "{{ filter_name }}" --type erratum --inclusion true
      loop : '{{ cv_list }}'
    
    - name: CV Filter rule is {{ filter_state }}
      redhat.satellite.content_view_filter_rule:
        server_url: '{{ satellite_url }}'
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: no
        organization: '{{ satellite_organization }}'
        content_view: '{{ item }}'
        content_view_filter: '{{ filter_name }}'
        start_date: '{{ filter_date }}'
        types:
          - security
          - enhancement
          - bugfix
        state: '{{ filter_state }}'
      loop : '{{ cv_list }}'
